### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by taejun52** [m1guelpf/auto-subtitle#100]
Hi, I've tried reinstalling ffmpeg several times using `pip install ffmpeg-python`, but i get this error no matter what i try, which includes having `--srt_only` set to true and using different models.

```
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\Scripts\auto_subtitle-script.py", line 33, in <module>
    sys.exit(load_entry_point('auto-subtitle==1.0', 'console_scripts', 'auto_subtitle')())
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_subtitle\cli.py", line 49, in main
    audios = get_audio(args.pop("video"))
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_subtitle\cli.py", line 78, in get_audio
    ffmpeg.input(path).output(
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by trobete** [comment]
It happened to me too.
You need to put the FFMPEG folder (exe, not python) in the "Path" variable -> https://phoenixnap.com/kb/ffmpeg-windows

<blockquote><img src="https://phoenixnap.com/kb/wp-content/uploads/2022/10/installing-ffmpeg-on-windows.png" width="48" align="right"><div>Knowledge Base by phoenixNAP</div><div><strong><a href="https://phoenixnap.com/kb/ffmpeg-windows">Installing FFmpeg on Windows {Step-by-Step}</a></strong></div><div>FFmpeg is a free command-line audio and video converter. Read this guide and learn how installing FFmpeg on Windows works.</div></blockquote>
