### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by nzcodes** [m1guelpf/auto-subtitle#102]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:...Python312\Scripts\auto_subtitle.exe\__main__.py", line 4, in <module>
  File "C:...Python312\Lib\site-packages\auto_subtitle\cli.py", line 2, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

I'm getting this error. I have ffmpeg installed both manually and with choco.

**Comment by zaltinsoy** [comment]
I believe the issue isn't related to the system's ffmpeg but rather to the "ffmpeg-python" library required for the project, just like [Issue 60](https://github.com/m1guelpf/auto-subtitle/issues/60) . This [PR](https://github.com/m1guelpf/auto-subtitle/pull/63) might resolve the problem. Additionally, I created a [fork](https://github.com/zaltinsoy/AutoSubZ) that incorporates the changes from that PR.

**Comment by omeiirr** [comment]
@zaltinsoy Thanks a ton for your fork! I was finally able to get this running. Any plans to merge into the original repo?

**Comment by zaltinsoy** [comment]
> @zaltinsoy Thanks a ton for your fork! I was finally able to get this running. Any plans to merge into the original repo?

I'm glad it helped you. Pull request is already waiting for the merge, but it looks like the original repo is not accepting any new changes.

**Comment by smith113-p** [comment]
Looks like this can also be resolves with `pip install ffmpeg-python`
