### ISSUE TITLE
 checkpoint = torch.load(fp, map_location=device) "Then nothing happens after getting this error message, Hangs forever..."

### ISSUE THREAD

**Issue by yekillanerm** [m1guelpf/auto-subtitle#105]
As above really, I run the command below and it runs for a while and them just does nothing after displaying "checkpoint = torch.load(fp, map_location=device)"

I admit I am super new to this and have been struggle and trying to follow all the information on this hub but keep running into issues. 

Any help appreciated! 

auto_subtitle f:\1/1.mkv --task translate --model large --language ja

/root/.local/pipx/venvs/auto-subtitle/lib/python3.10/site-packages/whisper/__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
 
 checkpoint = torch.load(fp, map_location=device)

**Comment by yekillanerm** [comment]
And now it has moved past and now has the following afterwards:-

  checkpoint = torch.load(fp, map_location=device)
Extracting audio from f:11...
Traceback (most recent call last):
  File "/root/.local/bin/auto_subtitle", line 8, in <module>
    sys.exit(main())
  File "/root/.local/pipx/venvs/auto-subtitle/lib/python3.10/site-packages/auto_subtitle/cli.py", line 49, in main
    audios = get_audio(args.pop("video"))
  File "/root/.local/pipx/venvs/auto-subtitle/lib/python3.10/site-packages/auto_subtitle/cli.py", line 81, in get_audio
    ffmpeg.input(path).output(
  File "/root/.local/pipx/venvs/auto-subtitle/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
