### ISSUE TITLE
Numpy runtime error

### ISSUE THREAD

**Issue by krysztofz** [m1guelpf/auto-subtitle#19]
Hi, I'm getting this error even though numpy is installed on my system. Any ideas? Thank you.

`/home/krysztof/.local/lib/python3.11/site-packages/torch/cuda/_utils.py:24: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:77.)
  device = torch.device(device)
Extracting audio from Quartetto Italiano (documentario - 2005)...
Generating subtitles for Quartetto Italiano (documentario - 2005)... This might take a while.
Traceback (most recent call last):
  File "/home/krysztof/.local/bin/auto_subtitle", line 33, in <module>
    sys.exit(load_entry_point('auto-subtitle==1.0', 'console_scripts', 'auto_subtitle')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krysztof/.local/lib/python3.11/site-packages/auto_subtitle/cli.py", line 43, in main
    subtitles = get_subtitles(
                ^^^^^^^^^^^^^^
  File "/home/krysztof/.local/lib/python3.11/site-packages/auto_subtitle/cli.py", line 99, in get_subtitles
    result = transcribe(audio_path)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krysztof/.local/lib/python3.11/site-packages/auto_subtitle/cli.py", line 44, in <lambda>
    audios, output_srt or srt_only, output_dir, lambda audio_path: model.transcribe(audio_path, **args)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krysztof/.local/lib/python3.11/site-packages/whisper/transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krysztof/.local/lib/python3.11/site-packages/whisper/audio.py", line 112, in log_mel_spectrogram
    audio = torch.from_numpy(audio)
            ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available`

**Comment by krysztofz** [comment]
Oh never mind, seems that the distro package manager had installed an older numpy. Deleting that and installing through pip again did the trick.
