### ISSUE TITLE
Errors about `ffmpeg`

### ISSUE THREAD

**Issue by scillidan** [m1guelpf/auto-subtitle#3]
It report errors:
```cmd
D:\home λ auto_subtitle High.Fidelity.2000.BluRay.1080p.DTS.x264-CHD.sample.mkv --model tiny -o sub/
Extracting audio from High.Fidelity.2000.BluRay.1080p.DTS.x264-CHD.sample...
Generating subtitles for High.Fidelity.2000.BluRay.1080p.DTS.x264-CHD.sample... This might take a while.
Detected language: english
Adding subtitles to High.Fidelity.2000.BluRay.1080p.DTS.x264-CHD.sample...
Traceback (most recent call last):
  File "C:\Users\scillidan\scoop\apps\python\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\scillidan\scoop\apps\python\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\scillidan\scoop\apps\python\current\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\scillidan\scoop\apps\python\current\lib\site-packages\auto_subtitle\cli.py", line 51, in main
    stderr = ffmpeg.concat(
  File "C:\Users\scillidan\scoop\apps\python\current\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```
My `ffmpeg` are there:
```
C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\ffmpeg.exe
C:\Users\scillidan\scoop\shims\ffmpeg.exe
C:\Users\scillidan\scoop\apps\jellyfin\current\system\ffmpeg.exe
```

**Comment by jackhax1** [comment]
Exact same error.

**Comment by mozrt2** [comment]
Same error for me.

**Comment by mozrt2** [comment]
Same error for me.

**Comment by liu246542** [comment]
Same error

**Comment by kevinle-1** [comment]
The FFmpeg subtitle filter doesn't like Windows paths (including the drive letter), and has trouble accessing the temporary .srt file to burn 😅
- https://stackoverflow.com/a/46854203 
- https://trac.ffmpeg.org/ticket/5754

```
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
...
[Parsed_subtitles_0 @ 000001a7fe874e00] Shaper: FriBidi 1.0.9 (SIMPLE)
[Parsed_subtitles_0 @ 000001a7fe874e00] Unable to open C\:\\Users\\kev\\AppData\\Local\\Temp\\myvideo.srt
[AVFilterGraph @ 000001a7fe85f500] Error initializing filter 'subtitles' with args 'C\\\:\\\\Users\\\\kev\\\\AppData\\\\Local\\\\Temp\\\\myvideo.srt:force_style=OutlineColour\=&H40000000,BorderStyle\=3'
Error initializing complex filters.
Invalid argument
```

As a temporary workaround, if you run `auto_subtitle` with `--output_srt true` in the same directory as your media file it will work (uses a relative path).

**Comment by scillidan** [comment]
Thanks, Man.
I reinstall it and the `dependencies`, from `source`.
It works now :)
```
Z: λ auto_subtitle in.mp4 --model tiny -o sub/ --output_srt true
Extracting audio from in...
Generating subtitles for in... This might take a while.
Detected language: english
Adding subtitles to in...
Saved subtitled video to Z:\sub\in.mp4.
```

**Comment by ezk06eer** [comment]
Hello, i have a similar error here:

```bash
(base) ➜  Movies auto_subtitle --output_srt true video.mkv ./sub/
Extracting audio from video...
Extracting audio from ...
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/bin/auto_subtitle", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/auto_subtitle/cli.py", line 42, in main
    audios = get_audio(args.pop("video"))
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/auto_subtitle/cli.py", line 77, in get_audio
    ffmpeg.input(path).output(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
(base) ➜  Movies
```

**Comment by Willywang8216** [comment]
Thanks kevinle-1 for pointing out the issue, which is exactly what I need.
[kevinle-1](https://github.com/kevinle-1)

Adding `import re` to the file `cli.py` and ` temp_dir = re.sub(r'\\','/',tempfile.gettempdir())` in the function `get_audio()`, the code works on my windows machine. 
Hope it'll be helpful for others.
