### ISSUE TITLE
Can't install on python 3.11.2x

### ISSUE THREAD

**Issue by igronus** [m1guelpf/auto-subtitle#41]
Hi,

I'm getting this error while trying to install it:

```
 $ pip3 install git+https://github.com/m1guelpf/auto-subtitle.git
Collecting git+https://github.com/m1guelpf/auto-subtitle.git
  Cloning https://github.com/m1guelpf/auto-subtitle.git to /private/var/folders/zb/cqpq69vs1f5fflqdw48fpcd40000gn/T/pip-req-build-fvbae_zv
  Running command git clone --filter=blob:none --quiet https://github.com/m1guelpf/auto-subtitle.git /private/var/folders/zb/cqpq69vs1f5fflqdw48fpcd40000gn/T/pip-req-build-fvbae_zv
  Resolved https://github.com/m1guelpf/auto-subtitle.git to commit b862a64ffa9570acc9588e6cb3e419053acabb9b
  Preparing metadata (setup.py) ... done
Collecting openai-whisper
  Using cached openai-whisper-20230314.tar.gz (792 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numba
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zb/cqpq69vs1f5fflqdw48fpcd40000gn/T/pip-install-5_e2o6hy/numba_ecc9ba83e7c942798174463b787dfd3d/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/zb/cqpq69vs1f5fflqdw48fpcd40000gn/T/pip-install-5_e2o6hy/numba_ecc9ba83e7c942798174463b787dfd3d/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Seems that my local installation of python/pip has no issues overall, I'm able to install/update other packages etc, so most probably it's an issue with this one.

**Comment by tobymuller233** [comment]
Changed python version to 3.7 works for me.
