### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by VasilyBakshaev** [m1guelpf/auto-subtitle#45]
Hi! I've got `ffmpeg error`

`(base) vasily@Vasilys-MacBook-Pro ~ % auto_subtitle /Users/vasily/video_77.mp4 -o subtitled/
100%|████████████████████████████████████████| 461M/461M [15:25<00:00, 523kiB/s]
Extracting audio from video_77...
Generating subtitles for video_77... This might take a while.
Detected language: Nynorsk
 99%|███████████████████████████████████▌| 282718/285718 [08:43<00:05, 540.21frames/s]
Adding subtitles to video_77...
Traceback (most recent call last):
  File "/Users/vasily/miniconda3/bin/auto_subtitle", line 8, in <module>
    sys.exit(main())
  File "/Users/vasily/miniconda3/lib/python3.10/site-packages/auto_subtitle/cli.py", line 58, in main
    ffmpeg.concat(
  File "/Users/vasily/miniconda3/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)`

Do you have any ideas how I can fix it?

**Comment by levfo** [comment]
I am having this same error.

**Comment by Huhnicorn** [comment]
same

**Comment by Kavan27** [comment]
any fixes yet?

**Comment by 326037785** [comment]
> I fixed it by fixing the path, I had /videos/video.mp4 changed it to videos/video.mp4

It did works， thx！！！guy！！
