### ISSUE TITLE
No module named 'ffmpeg'

### ISSUE THREAD

**Issue by Aenigma** [m1guelpf/auto-subtitle#60]
I kept getting an error when running auto-subtitle:

```
ModuleNotFoundError: No module named 'ffmpeg'
```

This seems to be caused by the fact that openai-whisper dropped the upstream dependency of `ffmpeg-python` in this change https://github.com/openai/whisper/commit/8035e9ef4890a06824a9a56a54d0feea9588f23b. Since this module depends on it, it should add the dependency to the `requirements.txt` and `setup.py`.

For now, you can do a workaround by running:

```
pip install ffmpeg-python
```

**Comment by whittinghamj** [comment]
pip install ffmpeg-python

that will fix your issue.

**Comment by whittinghamj** [comment]
lol i didn't read the last line before posting :P

**Comment by MoSattler** [comment]
Same problem here on Mac:

```
user@users-MacBook-Pro ~ % brew install ffmpeg     
Warning: ffmpeg 6.0_2 is already installed and up-to-date.
To reinstall 6.0_2, run:
  brew reinstall ffmpeg
  
user@users-MacBook-Pro ~ % auto_subtitle --help
Traceback (most recent call last):
  File "/opt/homebrew/bin/auto_subtitle", line 5, in <module>
    from auto_subtitle.cli import main
  File "/opt/homebrew/lib/python3.11/site-packages/auto_subtitle/cli.py", line 2, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'
```

**Comment by TheShiningBoots** [comment]
Can confirm, occurs on windows, even when ffmpeg is downloaded with the `choco` package manager.

**Comment by superresistant** [comment]
> pip install ffmpeg-python
> 
> that will fix your issue.

This causes a new issue

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_subtitle\cli.py", line 
67, in main
    ).output(out_path).run(quiet=True, overwrite_output=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by superresistant** [comment]
> > pip install ffmpeg-python
> > that will fix your issue.
> 
> This causes a new issue
> 
> ```
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_subtitle\cli.py", line 
> 67, in main
>     ).output(out_path).run(quiet=True, overwrite_output=True)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\ffmpeg\_run.py", line 325, in run
>     raise Error('ffmpeg', out, err)
> ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
> ```

This commit fixed the issue 
Fix ffmpeg subtitle overlay#81
