### ISSUE TITLE
ffmpeg run error

### ISSUE THREAD

**Issue by cricketlova** [m1guelpf/auto-subtitle#71]
not sure what this means on mac

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/auto_subtitle", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/auto_subtitle/cli.py", line 49, in main
    audios = get_audio(args.pop("video"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/auto_subtitle/cli.py", line 84, in get_audio
    ).run(quiet=True, overwrite_output=True)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by rapgoph** [comment]
I had the same error. Instead, I just added "--srt_only True" to make it work. Something like this...

auto_subtitle /path/to/video.mp4 ---model medium --srt_only True
