### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by thboon3** [m1guelpf/auto-subtitle#78]
Error I received:

C:\Users\user\Downloads>python Subtitles.py
Extracting audio from S1E01...
Generating subtitles for S1E01... This might take a while.
Detected language: English
 90%|█████████████████████████████████████████████████████████████▉       | 131739/146739 [07:44<00:52, 283.83frames/s]
Adding subtitles to S1E01...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\miniconda3\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\miniconda3\Lib\site-packages\auto_subtitle\cli.py", line 67, in main
    ).output(out_path).run(quiet=True, overwrite_output=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\Lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

I installed ffmpeg with pip install ffmpeg-python in my base env (before I used it with choco but I received an error saying ffmpeg couldn't be found). 

I've put my .py file and the .mp4 file both in my Downloads folder, this is the content of the .py file:

import os
os.system('auto_subtitle "Downloads/S1E01.mp4" -o subtitled/')

Not sure what I did wrong. 

Edit: I don't have an output folder (subtitled/) but I imagine this will get created if not found. 

This is the full stderr: 

stderr output:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\miniconda3\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\miniconda3\Lib\site-packages\auto_subtitle\cli.py", line 49, in main
    audios = get_audio(args.pop("video"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\Lib\site-packages\auto_subtitle\cli.py", line 84, in get_audio
    ).run(quiet=True, overwrite_output=True)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\miniconda3\Lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by bluepanda999** [comment]
I also get this error. It gets stuck, you need to kill the ffmpeg process for it to proceed.
I run this on a headless server to generate transcription by batches. Hopefully it gets fixed soon.

**Comment by Nishan666** [comment]
try:
`pip install ffmpeg-python
`
instead of:
`pip install ffmpeg`

**Comment by thboon3** [comment]
> try: `pip install ffmpeg-python ` instead of: `pip install ffmpeg`

I did.

**Comment by Nishan666** [comment]
### Error Correction and Usage Enhancement

#### Issue:
The command provided in the previous section encounters errors due to incorrect formatting and potential flag functionality issues.

#### Corrections:
- **Quotation Marks:** Remove unnecessary double quotes around the file path.
- **Flag Functionality:** Address potential issues with the -o flag.
- **Direct Terminal Usage:** Suggest executing the command directly in the terminal for simplicity.

#### Correct Command:
```bash
auto_subtitle /home/nick/auto-subtitle/test1.mp4 --model tiny --srt_only True
```

## Repository Reference:
#### For extracting subtitles from multiple videos simultaneously and obtaining both .vtt and .srt files, refer to my altered repository, similar to the provided command structure.

[auto-subtitle Repository](https://github.com/Nishan666/auto-subtitle)
Please refer to the last section of the README.md in the above Git repository for detailed instructions on how to perform bulk extraction of subtitles for all the videos in the folder

**Comment by MattiasLevlin** [comment]
I can confirm that the suggested option by @Nishan666 worked for me, i.e. passing `--srt_only True` as a flag additionally to the base command 👍 (OS: Windows 11)

```bash
# Not OK,  ffmpeg error
auto_subtitle video.mp4 -o subtitled/

# OK! Everything works and subtitles are printed to subtitled/ folder
auto_subtitle video.mp4 -o subtitled/ --srt_only True
```

**Edit**: Actually it appears that this issue and the same solution were both posted last year (2023):
https://github.com/m1guelpf/auto-subtitle/issues/50

**Comment by Mashinow** [comment]
I tried to fix this error https://github.com/m1guelpf/auto-subtitle/pull/81

**Comment by marcpozas** [comment]
> I tried to fix this error #81

Your commit works perfectly for me. Thank you!

**Comment by Delivator** [comment]
> try: `pip install ffmpeg-python ` instead of: `pip install ffmpeg`

Thank you!!

**Comment by slyt** [comment]
I got the error when I spelled my input video incorrectly.

**Comment by TheRealMiRRoRMaN** [comment]
> I tried to fix this error #81

this fix works perfectly, thank you so much. also to the creator of this app: to a weeb like myself you are a life saver. now i never need to worry anymore when an episode of a show is broken i can just use this tool and sub it myself. its so awesome. it does a great job at it too. so both the creator of this app and mashinow ARIGATO! thank you so much!
