### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Rakushoi** [m1guelpf/auto-subtitle#85]
Hi, i tried to use this package to subtitle a video but i get this error message every time, would be nice if sb could help me with this error message 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Name\anaconda3\envs\auto-translate\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\Name\anaconda3\envs\auto-translate\Lib\site-packages\auto_subtitle\cli.py", line 49, in main
    audios = get_audio(args.pop("video"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Name\anaconda3\envs\auto-translate\Lib\site-packages\auto_subtitle\cli.py", line 84, in get_audio
    ).run(quiet=True, overwrite_output=True)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Name\anaconda3\envs\auto-translate\Lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
              ^^^^^^^^^^
  File "C:\Users\Name\anaconda3\envs\auto-translate\Lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Name\anaconda3\envs\auto-translate\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Name\anaconda3\envs\auto-translate\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by zaltinsoy** [comment]
I solved a similar file / folder problem with https://github.com/m1guelpf/auto-subtitle/pull/81, it might be helpful for this case too.

**Comment by lzmunch** [comment]
I got the same error from the ffmpeg package and was able to fix it by making sure my ffmpeg exe was in my system path (windows as well).
