### ISSUE TITLE
 raise Error('ffmpeg', out, err) ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

### ISSUE THREAD

**Issue by Chapster5** [m1guelpf/auto-subtitle#92]
Hi all,

First up I am in no way clued up with Python it's took me the best part of 2 hours to even get this far with intalling python on windows and FFMPEG and downgrading Numpy as it wouldn't find 2.0.0 apparently. I installed FFMPEG using

`pip install ffmpeg-python` 

That says that it's been satisifed but python couldn't find it so I had to take an FFMPEG installating from a media server I have and copy and paste FFMPEG.exe along with its DLL files into system32 on windows. Now I am getting as far as below and can't seem to get any further. Not sure what I have to do now I have even edited "cli.py" with the below github suggested fix and that hasn't worked either:

https://github.com/m1guelpf/auto-subtitle/pull/81/commits/f91096d3ade2fb18f866ab7133e97558028e794c

Could anyone shed any light on what I am doing wrong please?

Thank you!!

```
C:\Users\Admin>auto_subtitle /F:/TV Shows/Benidorm S01-S10 720p WEB-DL H265 BONE/Season 9/Benidorm S09E01 720p WEB-DL H265 BONE.mp4 --model tiny --srt_only True
100%|█████████████████████████████████████| 72.1M/72.1M [00:05<00:00, 15.1MiB/s]
Extracting audio from TV...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\auto_subtitle\cli.py", line 49, in main
    audios = get_audio(args.pop("video"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\auto_subtitle\cli.py", line 93, in get_audio
    ).run(quiet=True, overwrite_output=True)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by CTG80** [comment]
Did you find a solution to this?  I'm running into it as well.

**Comment by Chapster5** [comment]
> Did you find a solution to this? I'm running into it as well.

I needed up ditching this software mate it never worked. I ended up running Bazarr server instead

**Comment by CTG80** [comment]
Good to know.  I'm doing the same.  Thanks for the reply!
