### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by superggfun** [m1guelpf/auto-subtitle#93]
I run the code, and raise ffmpeg error.
```
C:\Users\21922>ffmpeg
ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Universal media converter
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```
```
C:\Users\21922\Videos>auto_subtitle trimmed_output.mp4 --model medium --language en
C:\Users\21922\AppData\Roaming\Python\Python312\site-packages\whisper\__init__.py:146: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
Extracting audio from trimmed_output...
Generating subtitles for trimmed_output... This might take a while.
 99%|███████████████████████████████████████████████████████████████████ | 622840/631840 [04:52<00:04, 2130.51frames/s]
Adding subtitles to trimmed_output...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\21922\AppData\Roaming\Python\Python312\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
  File "C:\Users\21922\AppData\Roaming\Python\Python312\site-packages\auto_subtitle\cli.py", line 67, in main
    ).output(out_path).run(quiet=True, overwrite_output=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\21922\AppData\Roaming\Python\Python312\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by eni9889** [comment]
I have the same error

**Comment by superggfun** [comment]
> I have the same error

Hello, that that day, I give up because the error. But today, I read the previous issue. It it the windows command line problem. You can read previous issue and solve then. like
```
auto_subtitle in.mp4 --model tiny -o sub/ --output_srt true
```

**Comment by Josepaezra** [comment]
https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/15

This solved it for me ([roblox_guard] solution) Download that dll and paste it in the system32 folder.

**Comment by antonioanerao** [comment]
Did you install `pip install ffmpeg` or `pip install ffmpeg-python`? 

[edit]
I had this issue a few minutes ago. The problema was the file name. I typed it wrong

**Comment by Abceus** [comment]
`--srt_only true` works too. I think the script tries to create a video with the same name and in the same folder as the original video or something like that.

**Comment by donpardo** [comment]
Installing ffmpeg-python rather than ffmpeg fixed this problem for me. Ubuntu 25.04
