### ISSUE TITLE
ModuleNotFoundError: No module named 'ffmpeg'

### ISSUE THREAD

**Issue by cardiobleed** [m1guelpf/auto-subtitle#97]
> > C:\Users\virus>auto_subtitle C:\Users\virus\Desktop\01-1. Introduction.mp4 --model tiny -o sub/ --output_srt true
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\virus\AppData\Local\Programs\Python\Python312\Scripts\auto_subtitle.exe\__main__.py", line 4, in <module>
>   File "C:\Users\virus\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_subtitle\cli.py", line 2, in <module>
>     import ffmpeg
> ModuleNotFoundError: No module named 'ffmpeg'

Help, I'm pretty sure I have ffmpeg installed and everything

**Comment by cardiobleed** [comment]
After installing ffmpeg-python, the error is still the same but just looks different, what do I do??

> C:\Windows\system32>auto_subtitle C:\Users\virus\Desktop\01-1. Introduction.mp4 -o subtitled/ --srt_only True
> C:\Users\virus\AppData\Local\Programs\Python\Python312\Lib\site-packages\whisper\__init__.py:146: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   checkpoint = torch.load(fp, map_location=device)
> Extracting audio from 01-1...
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\virus\AppData\Local\Programs\Python\Python312\Scripts\auto_subtitle.exe\__main__.py", line 7, in <module>
>   File "C:\Users\virus\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_subtitle\cli.py", line 49, in main    audios = get_audio(args.pop("video"))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\virus\AppData\Local\Programs\Python\Python312\Lib\site-packages\auto_subtitle\cli.py", line 84, in get_audio
>     ).run(quiet=True, overwrite_output=True)
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\virus\AppData\Local\Programs\Python\Python312\Lib\site-packages\ffmpeg\_run.py", line 325, in run
>     raise Error('ffmpeg', out, err)
> ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

<blockquote><img src="https://opengraph.githubassets.com/8859aa61230041364d240c3553a49eae9c0f1ef88dd9e46e4a81acf9e61b5412/pytorch/pytorch" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pytorch/pytorch/blob/main/SECURITY.md">pytorch/SECURITY.md at main · pytorch/pytorch</a></strong></div><div>Tensors and Dynamic neural networks in Python with strong GPU acceleration - pytorch/pytorch</div></blockquote>

**Comment by cardiobleed** [comment]
https://github.com/m1guelpf/auto-subtitle/pull/81

This helped
